/*author:plapacz6@gmail.com, data:2023-01-03, licence: GPLv3*/
#ifndef ADD_TM2NOWTM_H
#define ADD_TM2NOWTM_H

#include <time.h>

#ifdef __cplusplus
extern "C" {
#endif


/**
 * @brief add struct tm to tm stuct generated by time()
 * 
 * @param tm1 strumt tm with time expressed as amount of time
 * @return struct tm - resulting time 
 *         after adding current time and amount of time from arg
 */
struct tm add_tm2nowtm(const struct tm tm1);



#ifdef __cplusplus
}
#endif

#endif // ADD_TM2NOWTM_H